
data:
  train:
    wav_scp: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//data//transcribe//wav.scp"
    text: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//data//transcribe//text"
  test:
    wav_scp: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//data//transcribe//wav.scp"
    text: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//data//transcribe//text"

predict:
  model_path: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//model"
  result_file: "./data/result"
  eval: 
    wav_scp: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//data//transcribe//wav.scp"
    text: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//data//transcribe//text"

dev_env:
  # 原始模型
  ori_model_path: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//whisper-tiny"
  # 转后的模型 - ct2-transformers-converter --model openai/whisper-tiny --output_dir whisper-tiny-ct2
  ctranslate_model_path: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//ctranslate"
  conf:
    # ['cuda','cpu']
    device: "cpu"
    # ['float16','int8_float16(run on GPU with INT8)','int8']
    compute_type: "float32"
  result_file: "./data/result_fast"
  dev:
    wav_scp: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//data//transcribe//wav.scp"
    text: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//example//aishell-sample//data//transcribe//text"


model:
  model_path: "C://Users//pony//Desktop//WhisperMultitaskFinetuning//whisper-tiny"
  is_large_model: False
  data_collator:
    forward_attention_mask: False
  model_train_argv:
    out_model_path: "./model"
    resume_from_checkpoint : ""
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 1
    num_train_epochs: 1
    learning_rate: 0.0001
    logging_steps: 2
    fp16: False
    warmup_steps: 50
    evaluation_strategy: "epoch"
    generation_max_length: 128
    remove_unused_columns: False
    label_names:
      - labels















